Database dev v2
Moejoe90/Lib-Connect pull request #7
Opened 2022-04-22 15:14 UTC by MaHDiaLaGaB

2022-04-22 23:34 UTC, Moejoe90 requested changes
Looks good we're almost there

2022-04-22 23:34 UTC, Moejoe90 commented on conftest.py
> +            'photo': 'http://s3.amazonaws.com/photos.sproutsocial.com/2022-04-14/2f1926ff-832a-4e26-81b7-ea8def6af7b4'
Hmmm storing images in the form of a link is a problem I would say as the photo might get deleted

2022-04-22 23:34 UTC, Moejoe90 commented on database.py
> +    def fine_page(self, page_name):
Find you mean here right?

2022-04-22 23:34 UTC, Moejoe90 commented on database.py
> +    def _create_relationship(self, tx, page_name, time):
You're still using time only instead of an md5 hash

2022-04-23 18:10 UTC, MaHDiaLaGaB commented on database.py
> +    def fine_page(self, page_name):
ops

2022-04-25 17:10 UTC, Moejoe90 requested changes
I left one request almost there :)

2022-04-25 17:10 UTC, Moejoe90 commented on test_database.py
> +from database import DataBase
Very nice tests

2022-04-25 17:10 UTC, Moejoe90 commented on database.py
> +        hashed_time = hashed_dict['time'].hexdigest()
_hash_everything should do this 

Basically here you do

hash = self._hash_everything. 

Also no need to seperate text and time I'll tell you more in the method

2022-04-25 17:10 UTC, Moejoe90 commented on database.py
> +                  'time': hashlib.md5(str(time).encode())}
it would make sense to return one hashed string here no need to seperate

2022-04-25 20:53 UTC, Moejoe90 approved these changes

2022-04-25 22:43 UTC, merged